config/routes.rb
Rails.application.routes.draw do

  root 'home#front'

  get 'home/login'
  post 'home/attempt_login'
  get 'home/logout'

  resources :alumnis do
    member do
      get :delete
      get :user_info
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alumni.rb
class Alumni < ApplicationRecord
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :degree,  presence: true
  validates :job_title,  presence: true
  validates :phone_number,  presence: true
  validates :graduation_year,  presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/alumnis_controller.rb
class AlumnisController < ApplicationController

  before_action :confirm_logged_in, :except => [:new, :create]

  def index
    @alumnis = Alumni.all
  end

  def show
    @alumni = Alumni.find(params[:id])
  end

  def user_info
    @alumni = Alumni.find(params[:id])
  end

  def new
    @alumni = Alumni.new
  end

  def create
    @alumni = Alumni.new(alumni_params)
    if @alumni.save
      session[:alumni_id] = @alumni.id
      redirect_to(user_info_alumni_path(@alumni))
    else
      render('new')
    end
  end

  def edit
    @alumni = Alumni.find(params[:id])
  end

  def update
    @alumni = Alumni.find(params[:id])
    if @alumni.update_attributes(alumni_params)
      redirect_to(user_info_alumni_path(@alumni))
    else
      render('edit')
    end
  end

  def delete
    @alumni = Alumni.find(params[:id])
  end

  def destroy
    @alumni = Alumni.find(params[:id])
    @alumni.destroy
    session[:alumni_id] = nil
    redirect_to(root_path)
  end

  private

  def alumni_params
    params.require(:alumni).permit(:first_name, :last_name, :email, :degree, :job_title, :phone_number, :graduation_year, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def confirm_logged_in
    unless session[:alumni_id]
      flash[:notice] = "Please log in"
      redirect_to(home_login_path)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def front
    # display home page
  end

  def login
    # login form
  end

  def attempt_login
    found_user = Alumni.where(:email => params[:email]).first
    if found_user
      authorized_user = found_user.authenticate(params[:password])
    end

    if authorized_user
      session[:alumni_id] = authorized_user.id
      redirect_to(user_info_alumni_path(authorized_user))
    else
      render('login')
    end
  end

  def logout
    session[:alumni_id] = nil
    redirect_to(root_path)
  end
end

app/helpers/alumnis_helper.rb
module AlumnisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/alumnis/delete.html.erb
<div class="alumnis delete">
  <h2>Delete Account</h2>

  <%= form_for(@alumni, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this account?</p>

    <p class="reference-name"><%= f.object.email %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Account") %>
    </div>

  <% end %>
</div>

app/views/alumnis/edit.html.erb
<div class="alumnis edit">
  <h2>Update Profile</h2>

  <%= form_for(@alumni) do |f| %>

    <table summary="Alumni form fields">
      <tr>
        <th>First name</th>
        <td><%= f.text_field(:first_name) %></td>
      </tr>
      <tr>
        <th>Last Name</th>
        <td><%= f.text_field(:last_name) %></td>
      </tr>
      <tr>
        <th>Phone Number</th>
        <td><%= f.text_field(:phone_number) %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= f.text_field(:email) %></td>
      </tr>
      <tr>
        <th>Graduation Year</th>
        <td><%= f.text_field(:graduation_year) %></td>
      </tr>
      <tr>
        <th>Degree</th>
        <td><%= f.text_field(:degree) %></td>
      </tr>
      <tr>
        <th>Job Title</th>
        <td><%= f.text_field(:job_title) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Account") %>
    </div>

  <% end %>

app/views/alumnis/index.html.erb
<div class="alumnis index">
  <h2>All Alumni</h2>

<!-- fix -->
  <%= link_to("Back to My Info", user_info_alumni_path(session[:alumni_id]), :class => 'action new') %>

  <table class="listing" summary="Alumni list">
    <tr class="header">
      <th>First Name</th>
      <th>Last Name</th>
      <th>Graduation Year</th>
      <th>More Info</th>
    </tr>
    <% @alumnis.each do |alumni| %>
    <tr>
      <td><%= alumni.first_name %></td>
      <td><%= alumni.last_name %></td>
      <td><%= alumni.graduation_year.to_i %></td>
      <td class="actions">
        <%= link_to("Show", alumni_path(alumni), :class => 'action show') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/alumnis/new.html.erb
<div class="alumnis new">
  <h2>Profile Information</h2>

  <%= form_for(@alumni) do |f| %>

    <table summary="Alumni form fields">
      <tr>
        <th>First name</th>
        <td><%= f.text_field(:first_name) %></td>
      </tr>
      <tr>
        <th>Last Name</th>
        <td><%= f.text_field(:last_name) %></td>
      </tr>
      <tr>
        <th>Phone Number</th>
        <td><%= f.text_field(:phone_number) %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= f.text_field(:email) %></td>
      </tr>
      <tr>
        <th>Graduation Year</th>
        <td><%= f.text_field(:graduation_year) %></td>
      </tr>
      <tr>
        <th>Degree</th>
        <td><%= f.text_field(:degree) %></td>
      </tr>
      <tr>
        <th>Job Title</th>
        <td><%= f.text_field(:job_title) %></td>
      </tr>
      <tr>
        <th>Password</th>
        <td><%= f.text_field(:password) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Account") %>
    </div>

  <% end %>
</div>

app/views/alumnis/show.html.erb
<%= link_to("<< Back to List", alumnis_path, :class => 'back-link') %>

<div class="alumnis show">
  <h2>Show Alumni</h2>

  <table summary="Alumni detail view">
    <tr>
      <th>First name</th>
      <td><%= @alumni.first_name %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= @alumni.last_name %></td>
    </tr>
    <tr>
      <th>Phone Number</th>
      <td><%= @alumni.phone_number.to_i %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @alumni.email %></td>
    </tr>
    <tr>
      <th>Graduation Year</th>
      <td><%= @alumni.graduation_year.to_i %></td>
    </tr>
    <tr>
      <th>Degree</th>
      <td><%= @alumni.degree %></td>
    </tr>
    <tr>
      <th>Job Title</th>
      <td><%= @alumni.job_title %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @alumni.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @alumni.updated_at %></td>
    </tr>
  </table>

</div>

app/views/alumnis/user_info.html.erb
<div class="alumnis show">
  <h2>Profile</h2>

  <table summary="Alumni detail view">
    <tr>
      <th>First name</th>
      <td><%= @alumni.first_name %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= @alumni.last_name %></td>
    </tr>
    <tr>
      <th>Phone Number</th>
      <td><%= @alumni.phone_number.to_i %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @alumni.email %></td>
    </tr>
    <tr>
      <th>Graduation Year</th>
      <td><%= @alumni.graduation_year.to_i %></td>
    </tr>
    <tr>
      <th>Degree</th>
      <td><%= @alumni.degree %></td>
    </tr>
    <tr>
      <th>Job Title</th>
      <td><%= @alumni.job_title %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @alumni.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @alumni.updated_at %></td>
    </tr>
  </table>

  <%= link_to("Edit Info", edit_alumni_path(@alumni), :class => 'action edit') %>
  <%= link_to("See All Info", alumnis_path(@alumni), :class => 'action show') %>
  <%= link_to("Delete User", delete_alumni_path(@alumni), :class => 'action delete') %>
  <%= link_to("Logout", home_logout_path) %>

</div>

app/views/home/front.html.erb
<div class="alumnis home">
  <img src="/assets/PBE_Logo.jpg" alt="PBE" style="display: block; margin-left: auto; margin-right: auto; margin-top: 5%">
  <h1 style="text-align: center;">Alumni Tracker</h1>

  <div style="text-align: center">
    <%= link_to("Log In", home_login_path) %>
    <%= link_to("Register", new_alumni_path, :class => 'action new') %>
  </div>
</div>

app/views/home/login.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="login">
  <%= form_tag(home_attempt_login_path, :method => :post) do %>
  <table>
    <tr>
      <td><%= label_tag(:email) %></td>
      <td><%= text_field_tag(:email, params[:email]) %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td><%= text_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag('Log In') %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlumniTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>